DROP TABLE nabidka_ke_koupi;
DROP TABLE zadost_o_prohlidku;
DROP TABLE kupni_smlouva;
DROP TABLE nemovitost;
DROP TABLE zamestnanec;
DROP TABLE zakaznik;
DROP TABLE zakaznik_s_radnym_uctem;

CREATE TABLE zamestnanec
(
    zamestnanec_ID
        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jmeno
        VARCHAR(60),
    datum_nastupu
        DATE,
    datum_vypovedi
        DATE,
    pozice
        VARCHAR(60)
);

CREATE TABLE zakaznik
(
    zakaznik_id
        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jmeno
        VARCHAR(60),
    email
        NVARCHAR2(60),
    CHECK (REGEXP_LIKE(
            email, '^[a-z]+[a-z0-9\.]*@[a-z0-9\.-]+\.[a-z]{2,}$', 'i'
        )),
    telefonni_cislo
        VARCHAR(20),
    login
        VARCHAR(18),
    heslo
        VARCHAR(256)
);


CREATE TABLE zakaznik_s_radnym_uctem
(
    zakaznik_ID
        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jmeno
        VARCHAR(60),
    email
        NVARCHAR2(60),
    CHECK (REGEXP_LIKE(
            email, '^[a-z]+[a-z0-9\.]*@[a-z0-9\.-]+\.[a-z]{2,}$', 'i'
        )),
    telefonni_cislo
        VARCHAR(20),
    login
        VARCHAR(18),
    heslo
        VARCHAR(256),
    adresa
        VARCHAR(1024),
    kategorie_zakaznika
        VARCHAR(16) CHECK (kategorie_zakaznika IN ('pravnicka osoba', 'fyzicka osoba'))
);


CREATE TABLE nemovitost
(
    nemovitost_ID
        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typ_nemovitosti
        VARCHAR(60),
    plocha
        INT CHECK ( plocha >= 0 ),
    poloha
        VARCHAR(200),
    cena
        DECIMAL(12, 3) CHECK ( cena >= 0 ),
    blizsi_popis
        VARCHAR(2048),
    zamestnanec
        INT DEFAULT NULL,
    vlastnik
        int,
    zakaznik
        int,
    CONSTRAINT  vlozil_do_systemu_fk
        FOREIGN KEY (zamestnanec) REFERENCES zamestnanec(zamestnanec_ID)
            ON DELETE SET NULL,
    CONSTRAINT vlastnik_fk
        FOREIGN KEY (vlastnik) REFERENCES zakaznik_s_radnym_uctem(zakaznik_ID)
            ON DELETE SET NULL
);

CREATE TABLE kupni_smlouva
(
    smlouva_ID
        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datum_uzavreni_smlouvy
        DATE,
    stav
        VARCHAR(20) CHECK ( stav IN ('uzavrena', 'neuzavrena')),
    obsah_smlouvy
        VARCHAR(4000),
    zakaznik
        INT,
    zamestnanec
        INT,
    nemovitost
        INT,
    CONSTRAINT figurujici_zakaznik_fk
        FOREIGN KEY (zakaznik) REFERENCES zakaznik_s_radnym_uctem(zakaznik_ID)
            ON DELETE SET NULL,
    CONSTRAINT zadal_zamestnanec_fk
        FOREIGN KEY (zamestnanec) REFERENCES zamestnanec(zamestnanec_ID)
            ON DELETE SET NULL,
    CONSTRAINT figurujici_nemovitost_fk
        FOREIGN KEY (nemovitost) REFERENCES nemovitost(nemovitost_ID)
            ON DELETE SET NULL
);

CREATE TABLE zadost_o_prohlidku
(
    zadost_ID
        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pozadovany_datum_a_cas_prohlidky
        DATE,
    datum_podani_zadosti
        TIMESTAMP,
    probehla
        VARCHAR(3) CHECK (probehla IN ('ano', 'ne')),
    nemovitost
        INT,
    zakaznik
        INT,
    CONSTRAINT prohlidka_nemovitosti_fk
        FOREIGN KEY (nemovitost) REFERENCES nemovitost(nemovitost_ID)
            ON DELETE SET NULL,
    CONSTRAINT zadajici_zakaznik_fk
        FOREIGN KEY (zakaznik) REFERENCES zakaznik(zakaznik_id)
            ON DELETE SET NULL
);

CREATE TABLE nabidka_ke_koupi
(
    nabidka_ID
        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vyse_nabidky
        DECIMAL(12, 3) CHECK ( vyse_nabidky >= 0 ),
    datum_podani_nabidky
        TIMESTAMP,
    nemovitost
        INT,
    zakaznik
        INT,
    CONSTRAINT zadana_nemovitost_fk
        FOREIGN KEY (nemovitost) REFERENCES nemovitost(nemovitost_ID)
            ON DELETE SET NULL,
    CONSTRAINT nabizejici_zakaznik_fk
        FOREIGN KEY (zakaznik) REFERENCES zakaznik(zakaznik_id)
            ON DELETE SET NULL
);

INSERT INTO zamestnanec
VALUES (default, 'josef', TO_DATE('2022-04-20', 'yyyy/mm/dd'), '2.2.2020', 'generalni reditel');
INSERT INTO zamestnanec
VALUES (default, 'josef', '1.1.2020', '2.2.2020', 'generalni reditel');
select * FROM zamestnanec;