DROP TABLE nabidky_ke_koupi;
DROP TABLE zadosti_o_prohlidku;
DROP TABLE kupni_smlouvy;
DROP TABLE nemovitosti;
DROP TABLE zamestnanci;
DROP TABLE zakaznici;
DROP TABLE zakaznici_s_radnym_uctem;

CREATE TABLE zamestnanci
(
    zamestnanci_ID
        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    jmeno
        VARCHAR(60) NOT NULL,
    datum_nastupu
        DATE NOT NULL,
    datum_vypovedi
        DATE NOT NULL,
    pozice
        VARCHAR(60)
);

CREATE TABLE zakaznici_s_radnym_uctem
(
    zakaznici_id_s_radnym_uctem_id
        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    adresa
        VARCHAR(1024) NOT NULL, -- zakaznici s radnym uctem se vyznacuje tim, ze o nem mame blizsi informace
    kategorie_zakaznicia
        VARCHAR(16) NOT NULL CHECK (kategorie_zakaznicia IN ('pravnicka osoba', 'fyzicka osoba'))
);

CREATE TABLE zakaznici
(
    zakaznici_id
        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    jmeno
        VARCHAR(60) NOT NULL,
    email
        NVARCHAR2(60),
    CHECK (REGEXP_LIKE(
            email, '^[a-z]+[a-z0-9\.]*@[a-z0-9\.-]+\.[a-z]{2,}$', 'i'
        )),
    telefonni_cislo
        VARCHAR(20) NOT NULL,
    login
        VARCHAR(18) NOT NULL,
    heslo
        VARCHAR(256) NOT NULL,
    zakaznici_s_radnym_uctem_fk
        INT DEFAULT NULL,
    CONSTRAINT zakaznici_s_radnym_uctem_fk
        FOREIGN KEY (zakaznici_s_radnym_uctem_fk) REFERENCES zakaznici_s_radnym_uctem (zakaznici_id_s_radnym_uctem_id)
            ON DELETE SET NULL
);

CREATE TABLE nemovitosti
(
    nemovitosti_ID
        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    typ_nemovitostii
        VARCHAR(60),
    plocha
        INT CHECK ( plocha >= 0 ),
    poloha
        VARCHAR(200),
    cena
        DECIMAL(12, 3) CHECK ( cena >= 0 ),
    blizsi_popis
        VARCHAR(2048),
    zamestnanci
        INT DEFAULT NULL,
    vlastnik
        INT DEFAULT NULL,
    zakaznici
        INT DEFAULT NULL,
    CONSTRAINT vlozil_do_systemu_fk
        FOREIGN KEY (zamestnanci) REFERENCES zamestnanci (zamestnanci_ID)
            ON DELETE SET NULL,
    CONSTRAINT vlastnik_fk
        FOREIGN KEY (vlastnik) REFERENCES zakaznici_s_radnym_uctem (zakaznici_id_s_radnym_uctem_id)
            ON DELETE SET NULL
);

CREATE TABLE kupni_smlouvy
(
    smlouva_ID
        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    datum_uzavreni_smlouvy
        DATE DEFAULT NULL,
    stav
        VARCHAR(20) DEFAULT 'neuzavrena' CHECK ( stav IN ('uzavrena', 'neuzavrena')),
    obsah_smlouvy
        VARCHAR(4000) NOT NULL,
    zakaznici
        INT DEFAULT NULL,
    zamestnanci
        INT DEFAULT NULL,
    nemovitosti
        INT DEFAULT NULL,
    CONSTRAINT figurujici_zakaznici_fk
        FOREIGN KEY (zakaznici) REFERENCES zakaznici_s_radnym_uctem (zakaznici_id_s_radnym_uctem_id)
            ON DELETE SET NULL,
    CONSTRAINT zadal_zamestnanci_fk
        FOREIGN KEY (zamestnanci) REFERENCES zamestnanci (zamestnanci_ID)
            ON DELETE SET NULL,
    CONSTRAINT figurujici_nemovitosti_fk
        FOREIGN KEY (nemovitosti) REFERENCES nemovitosti (nemovitosti_ID)
            ON DELETE SET NULL
);

CREATE TABLE zadosti_o_prohlidku
(
    zadost_ID
        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    pozadovany_datum_a_cas_prohlidky
        DATE NOT NULL,
    datum_podani_zadosti
        TIMESTAMP,
    probehla
        VARCHAR(3) DEFAULT 'ne' CHECK (probehla IN ('ano', 'ne')),
    nemovitosti
        INT DEFAULT NULL,
    zakaznici
        INT DEFAULT NULL,
    CONSTRAINT prohlidka_nemovitostii_fk
        FOREIGN KEY (nemovitosti) REFERENCES nemovitosti (nemovitosti_ID)
            ON DELETE SET NULL,
    CONSTRAINT zadajici_zakaznici_fk
        FOREIGN KEY (zakaznici) REFERENCES zakaznici (zakaznici_id)
            ON DELETE SET NULL
);

CREATE TABLE nabidky_ke_koupi
(
    nabidka_ID
        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    vyse_nabidky
        DECIMAL(12, 3) NOT NULL CHECK ( vyse_nabidky >= 0 ),
    datum_podani_nabidky
        TIMESTAMP,
    nemovitosti
        INT DEFAULT NULL,
    zakaznici
        INT DEFAULT NULL,
    CONSTRAINT zadana_nemovitosti_fk
        FOREIGN KEY (nemovitosti) REFERENCES nemovitosti (nemovitosti_ID)
            ON DELETE SET NULL,
    CONSTRAINT nabizejici_zakaznici_fk
        FOREIGN KEY (zakaznici) REFERENCES zakaznici (zakaznici_id)
            ON DELETE SET NULL
);

INSERT INTO zamestnanci
VALUES (default, 'Josef Novák', TO_DATE('2022-04-20', 'yyyy/mm/dd'), '2.2.2020', 'generalni reditel');
INSERT INTO zamestnanci
VALUES (default, 'Erik Malina', '2-1-2019', '5.12.2021', 'delnik');
INSERT INTO zamestnanci
VALUES (default, 'Dominik Krátký', '6-1-2019', '7.2.2020', 'uklizec');

INSERT INTO zakaznici_s_radnym_uctem
VALUES (DEFAULT, 'Brno Pisárky 10', 'pravnicka osoba');
INSERT INTO zakaznici_s_radnym_uctem
VALUES (DEFAULT, 'Praha 7', 'fyzicka osoba');

INSERT INTO zakaznici
VALUES (DEFAULT, 'Emil Houba', 'emil@houba.cz', '608233610', 'xEmil00',
        'bf334e5e36c768f5191ae384ed809d105ba3c4b8bc7d59b856d43da7ec148758', NULL);
INSERT INTO zakaznici
VALUES (DEFAULT, 'Jana černochová', 'jana.cernochova@mo.cz', '+420 225 200 400', 'xJanaObrana00',
        '504e96ff7de999afa6b71721456f78a3f2ecdbb43f20a5b9c85ebbb39b9bc40c', NULL);
INSERT INTO zakaznici
VALUES (DEFAULT, 'Karolína Pepsi', 'kajicka@kocicka.cz', '+420 2544 655 887', 'xKaja44',
        'f3451762d2d128b241bf02a70b2232c9ddbd227a6f368b66c6ace938957d9141', 2);

INSERT INTO nemovitosti
VALUES (default, 'chata', 84, 'praha 8', 25000000.99, 'je to v centru prahy', 1, 1, 1);
INSERT INTO nemovitosti
VALUES (default, 'dum', 152, 'brno', 250000.99, 'je to na kralove poli.', 2, 2, 1);
INSERT INTO nemovitosti
VALUES (default, 'byt', 42, 'uhersky brod', 2500.98, 'je to v centru brodu', 1, 2, 3);

INSERT INTO kupni_smlouvy
VALUES (DEFAULT, '4.4.2019', 'uzavrena', 'Koupite nemovitosti c.3 za 250000kc', 2, 2, 3);
INSERT INTO kupni_smlouvy
VALUES (DEFAULT, NULL, 'neuzavrena', 'Koupite nemovitosti c.2 za 11111kc', 2, 1, 1);

INSERT INTO zadosti_o_prohlidku
VALUES (DEFAULT, '2.5.2022', CURRENT_TIMESTAMP, 'ne', 2, 2);
INSERT INTO zadosti_o_prohlidku
VALUES (DEFAULT, '2.7.2020', CURRENT_TIMESTAMP, 'ano', 1, 3);

INSERT INTO nabidky_ke_koupi
VALUES (DEFAULT, 5000000, CURRENT_TIMESTAMP, 3, 3);
INSERT INTO nabidky_ke_koupi
VALUES (DEFAULT, 125000, CURRENT_TIMESTAMP, 1, 2);

-- SELECT *
-- FROM zamestnanci;
-- SELECT *
-- FROM zakaznici;
-- SELECT *
-- FROM zakaznici_s_radnym_uctem;
-- SELECT *
-- FROM nemovitosti;
-- SELECT *
-- FROM zadosti_o_prohlidku;
-- SELECT *
-- FROM nabidky_ke_koupi;
-- SELECT *
-- FROM kupni_smlouvy;